### ISSUE TITLE
"--limit" behaving oddly?

### ISSUE THREAD

**Issue by mittimithai** [3c7/bazaar#6]
I seem to be getting non deterministic returns from my queries,

 malwarebazzar % bazaar query --limit 900 -s tag ransomware  | wc -l
    1170

 malwarebazzar % bazaar query --limit 900 -s tag ransomware  | wc -l
    1317

Another example:

malwarebazzar % bazaar query --limit 300 -c -s tag ransomware  | wc -l
     301
malwarebazzar % bazaar query --limit 900 -c -s tag ransomware  | wc -l
     901
malwarebazzar % bazaar query --limit 1000 -c -s tag ransomware  | wc -l
    1001
malwarebazzar % bazaar query --limit 2000 -c -s tag ransomware  | wc -l
     101

There doesn't seem to be a lot going on in the code that could cause this so I think it is on the server side, but has anyone observed this behavior? I am just trying to get all the ransomware binaries on malware bazaar...

**Comment by 3c7** [comment]
This is probably because the CSV output somehow a) breaks lines because of your terminal width or b) has linebreaks in it. If you just query via the `--simple` switch, the amount of results is as expected:

```
❯ bazaar query tag ransomware --limit 10 -s | wc -l
10
❯ bazaar query tag ransomware --limit 100 -s | wc -l
100
❯ bazaar query tag ransomware --limit 150 -s | wc -l
150
❯ bazaar query tag ransomware --limit 250 -s | wc -l
250
❯ bazaar query tag ransomware --limit 500 -s | wc -l
500
❯ bazaar query tag ransomware --limit 1000 -s | wc -l
1000
```

The latter example is correct, as the CSV output also contains headers for the columns.

**Comment by 3c7** [comment]
Also, 1000 seems to be the API limit and therefore only 100 results are returned if you try to query more than 1000 Samples.
