### ISSUE TITLE
Upgrade PyYAML

### ISSUE THREAD

**Issue by fishfacegit** [3c7/bazaar#9]
Is it possible to upgrade the version of the PyYAML dependency? I face errors with wheel and versions below 6.0.1.

```
Collecting PyYAML<6.0.0,>=5.4.1 (from malwarebazaar->-r requirements.txt (line 3))
  Downloading PyYAML-5.4.1.tar.gz (175 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 kB 17.2 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [68 lines of output]
```

**Comment by 3c7** [comment]
Try updating `malwarebazaar`, in v0.2.4 PyYAML is already at ^6.0.1 - maybe you use a cached version?

https://github.com/3c7/bazaar/blob/fa98beba6512e73ed0fc5b332b533654fec263a1/pyproject.toml#L18-L25
https://github.com/3c7/bazaar/blob/fa98beba6512e73ed0fc5b332b533654fec263a1/poetry.lock#L390-L394

**Comment by fishfacegit** [comment]
I had another package forcing malwarebazaar to be installed in an outdated version.
